/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDomainHeadIndexRouteImport } from './routes/_authenticated/domain-head/index'
import { Route as AuthenticatedComplaintsIndexRouteImport } from './routes/_authenticated/complaints/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedDomainHeadAssignmentsRouteImport } from './routes/_authenticated/domain-head/assignments'
import { Route as AuthenticatedComplaintsSubmitRouteImport } from './routes/_authenticated/complaints/submit'
import { Route as AuthenticatedComplaintsIdRouteImport } from './routes/_authenticated/complaints/$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminDomainsRouteImport } from './routes/_authenticated/admin/domains'
import { Route as AuthenticatedDomainHeadReviewIdRouteImport } from './routes/_authenticated/domain-head/review/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDomainHeadIndexRoute =
  AuthenticatedDomainHeadIndexRouteImport.update({
    id: '/domain-head/',
    path: '/domain-head/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplaintsIndexRoute =
  AuthenticatedComplaintsIndexRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDomainHeadAssignmentsRoute =
  AuthenticatedDomainHeadAssignmentsRouteImport.update({
    id: '/domain-head/assignments',
    path: '/domain-head/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplaintsSubmitRoute =
  AuthenticatedComplaintsSubmitRouteImport.update({
    id: '/complaints/submit',
    path: '/complaints/submit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplaintsIdRoute =
  AuthenticatedComplaintsIdRouteImport.update({
    id: '/complaints/$id',
    path: '/complaints/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDomainsRoute =
  AuthenticatedAdminDomainsRouteImport.update({
    id: '/admin/domains',
    path: '/admin/domains',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDomainHeadReviewIdRoute =
  AuthenticatedDomainHeadReviewIdRouteImport.update({
    id: '/domain-head/review/$id',
    path: '/domain-head/review/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/complaints/submit': typeof AuthenticatedComplaintsSubmitRoute
  '/domain-head/assignments': typeof AuthenticatedDomainHeadAssignmentsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/domain-head/': typeof AuthenticatedDomainHeadIndexRoute
  '/domain-head/review/$id': typeof AuthenticatedDomainHeadReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/complaints/submit': typeof AuthenticatedComplaintsSubmitRoute
  '/domain-head/assignments': typeof AuthenticatedDomainHeadAssignmentsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/complaints': typeof AuthenticatedComplaintsIndexRoute
  '/domain-head': typeof AuthenticatedDomainHeadIndexRoute
  '/domain-head/review/$id': typeof AuthenticatedDomainHeadReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/_authenticated/complaints/submit': typeof AuthenticatedComplaintsSubmitRoute
  '/_authenticated/domain-head/assignments': typeof AuthenticatedDomainHeadAssignmentsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/_authenticated/domain-head/': typeof AuthenticatedDomainHeadIndexRoute
  '/_authenticated/domain-head/review/$id': typeof AuthenticatedDomainHeadReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/domains'
    | '/admin/users'
    | '/complaints/$id'
    | '/complaints/submit'
    | '/domain-head/assignments'
    | '/admin/'
    | '/complaints/'
    | '/domain-head/'
    | '/domain-head/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/domains'
    | '/admin/users'
    | '/complaints/$id'
    | '/complaints/submit'
    | '/domain-head/assignments'
    | '/admin'
    | '/complaints'
    | '/domain-head'
    | '/domain-head/review/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/admin/domains'
    | '/_authenticated/admin/users'
    | '/_authenticated/complaints/$id'
    | '/_authenticated/complaints/submit'
    | '/_authenticated/domain-head/assignments'
    | '/_authenticated/admin/'
    | '/_authenticated/complaints/'
    | '/_authenticated/domain-head/'
    | '/_authenticated/domain-head/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domain-head/': {
      id: '/_authenticated/domain-head/'
      path: '/domain-head'
      fullPath: '/domain-head/'
      preLoaderRoute: typeof AuthenticatedDomainHeadIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints/': {
      id: '/_authenticated/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthenticatedComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domain-head/assignments': {
      id: '/_authenticated/domain-head/assignments'
      path: '/domain-head/assignments'
      fullPath: '/domain-head/assignments'
      preLoaderRoute: typeof AuthenticatedDomainHeadAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints/submit': {
      id: '/_authenticated/complaints/submit'
      path: '/complaints/submit'
      fullPath: '/complaints/submit'
      preLoaderRoute: typeof AuthenticatedComplaintsSubmitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints/$id': {
      id: '/_authenticated/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthenticatedComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/domains': {
      id: '/_authenticated/admin/domains'
      path: '/admin/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthenticatedAdminDomainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domain-head/review/$id': {
      id: '/_authenticated/domain-head/review/$id'
      path: '/domain-head/review/$id'
      fullPath: '/domain-head/review/$id'
      preLoaderRoute: typeof AuthenticatedDomainHeadReviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminDomainsRoute: typeof AuthenticatedAdminDomainsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedComplaintsIdRoute: typeof AuthenticatedComplaintsIdRoute
  AuthenticatedComplaintsSubmitRoute: typeof AuthenticatedComplaintsSubmitRoute
  AuthenticatedDomainHeadAssignmentsRoute: typeof AuthenticatedDomainHeadAssignmentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedComplaintsIndexRoute: typeof AuthenticatedComplaintsIndexRoute
  AuthenticatedDomainHeadIndexRoute: typeof AuthenticatedDomainHeadIndexRoute
  AuthenticatedDomainHeadReviewIdRoute: typeof AuthenticatedDomainHeadReviewIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminDomainsRoute: AuthenticatedAdminDomainsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedComplaintsIdRoute: AuthenticatedComplaintsIdRoute,
  AuthenticatedComplaintsSubmitRoute: AuthenticatedComplaintsSubmitRoute,
  AuthenticatedDomainHeadAssignmentsRoute:
    AuthenticatedDomainHeadAssignmentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedComplaintsIndexRoute: AuthenticatedComplaintsIndexRoute,
  AuthenticatedDomainHeadIndexRoute: AuthenticatedDomainHeadIndexRoute,
  AuthenticatedDomainHeadReviewIdRoute: AuthenticatedDomainHeadReviewIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
